DROP TABLE OAUTH_ACCESS_TOKEN CASCADE CONSTRAINTS PURGE;
CREATE TABLE OAUTH_ACCESS_TOKEN
(
   TOKEN_ID           VARCHAR2(256 Byte),
   TOKEN              BLOB,
   AUTHENTICATION_ID  VARCHAR2(256 Byte),
   USER_NAME          VARCHAR2(256 Byte),
   CLIENT_ID          VARCHAR2(256 Byte),
   AUTHENTICATION     BLOB,
   REFRESH_TOKEN      VARCHAR2(256 Byte)
)
TABLESPACE FCNJAVA;

-------------------
DROP TABLE OAUTH_CLIENT_DETAILS CASCADE CONSTRAINTS PURGE;
CREATE TABLE OAUTH_CLIENT_DETAILS
(
   CLIENT_ID                VARCHAR2(256 Byte)    NOT NULL,
   RESOURCE_IDS             VARCHAR2(256 Byte),
   CLIENT_SECRET            VARCHAR2(256 Byte),
   SCOPE                    VARCHAR2(256 Byte),
   AUTHORIZED_GRANT_TYPES   VARCHAR2(256 Byte),
   WEB_SERVER_REDIRECT_URI  VARCHAR2(256 Byte),
   AUTHORITIES              VARCHAR2(256 Byte),
   ACCESS_TOKEN_VALIDITY    NUMBER,
   REFRESH_TOKEN_VALIDITY   NUMBER,
   ADDITIONAL_INFORMATION   VARCHAR2(1024 Byte),
   AUTOAPPROVE              VARCHAR2(256 Byte)
)
TABLESPACE FCNJAVA;

ALTER TABLE OAUTH_CLIENT_DETAILS
   ADD CONSTRAINT OAUTH_CLIENT_DETAILS_PK
   PRIMARY KEY (CLIENT_ID) 
   USING INDEX TABLESPACE FCNJAVA;




INSERT INTO OAUTH_CLIENT_DETAILS
(
  CLIENT_ID,
  RESOURCE_IDS,
  CLIENT_SECRET,
  SCOPE,
  AUTHORIZED_GRANT_TYPES,
  WEB_SERVER_REDIRECT_URI,
  AUTHORITIES,
  ACCESS_TOKEN_VALIDITY,
  REFRESH_TOKEN_VALIDITY,
  ADDITIONAL_INFORMATION,
  AUTOAPPROVE
)
VALUES
(
  'appclient',
  'product_info_api',
  'secret',
  'read,write',
  'password,refresh_token',
  'redirect_uri',
  'ROLE_CLIENT,ROLE_TRUSTED_CLIENT',
  120,
  10,
  '{}',
  NULL
);





-----
DROP TABLE OAUTH_REFRESH_TOKEN CASCADE CONSTRAINTS PURGE;
CREATE TABLE OAUTH_REFRESH_TOKEN
(
   TOKEN_ID        VARCHAR2(256 Byte),
   TOKEN           BLOB,
   AUTHENTICATION  BLOB
)
TABLESPACE FCNJAVA;


